### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by drupol** [tkellogg/dura#72]
Hello,

This morning I upgraded rust to version 1.58 and I'm unable to run the tests. Did I do something wrong perhaps?

Here's the full log:

<details>

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ git log -1
commit 1e1834dba821f2a8c87fca8aa6eaa00e24367512 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Author: dswij <44697459+dswij@users.noreply.github.com>
Date:   Fri Jan 14 14:18:03 2022 +0800

    chore: cleanup (#71)
$ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running unittests (target/debug/deps/dura-19f8404b8c118cb7)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/dura-73e01f6fdd7170ac)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/snapshots_test.rs (target/debug/deps/snapshots_test-e0f46cebc7bd3656)

running 6 tests
test test_commit_signature_exclude_git_config ... FAILED
test no_changes ... ok
test test_commit_signature_using_dura_config ... FAILED
test test_commit_signature_using_git_config ... FAILED
test change_single_file ... ok
test during_merge_conflicts ... ok

failures:

---- test_commit_signature_exclude_git_config stdout ----
$ git init
Initialized empty Git repository in /tmp/nix-shell.Ea9V9N/.tmpEIXWS4/.git/

$ git checkout -b master
Switched to a new branch 'master'

$ git config user.name git-author
$ git config user.email git@someemail.com
$ echo 'initial rev' > foo.txt
$ git add .
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   config.toml
        new file:   foo.txt


$ git commit -m test
$ echo 'change 1' > foo.txt
thread 'test_commit_signature_exclude_git_config' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }', tests/snapshots_test.rs:150:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_commit_signature_using_dura_config stdout ----
$ git init
Initialized empty Git repository in /tmp/nix-shell.Ea9V9N/.tmp4XRp2A/.git/

$ git checkout -b master
Switched to a new branch 'master'

$ git config user.name git-author
$ git config user.email git@someemail.com
$ echo 'initial rev' > foo.txt
$ git add .
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   config.toml
        new file:   foo.txt


$ git commit -m test
$ echo 'change 1' > foo.txt
thread 'test_commit_signature_using_dura_config' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }', tests/snapshots_test.rs:94:57

---- test_commit_signature_using_git_config stdout ----
$ git init
Initialized empty Git repository in /tmp/nix-shell.Ea9V9N/.tmpl3X4RV/.git/

$ git checkout -b master
Switched to a new branch 'master'

$ git config user.name git-author
$ git config user.email git@someemail.com
$ echo 'initial rev' > foo.txt
$ git add .
$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   config.toml
        new file:   foo.txt


$ git commit -m test
$ echo 'change 1' > foo.txt
thread 'test_commit_signature_using_git_config' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }', tests/snapshots_test.rs:120:57


failures:
    test_commit_signature_exclude_git_config
    test_commit_signature_using_dura_config
    test_commit_signature_using_git_config

test result: FAILED. 3 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.29s

error: test failed, to rerun pass '--test snapshots_test'
$
```

</details>

**Comment by tkellogg** [comment]
these are all new tests, and they did some mildly suspicious things, however they did used to pass. I'll take a look in a few hours.

**Comment by tkellogg** [comment]
I can reproduce this on Mac. Seeing if I can patch it quickly...

**Comment by drupol** [comment]
Thanks!
